let fixture = [
    {
        "match_id": 2277789,
        "points": 0,
        "team_1": "Qatar",
        "team_1_id": 1873,
        "team_2": "Ecuador",
        "team_2_id": 830,
        "goal_1": 2,
        "goal_2": 2,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-20T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 36766,
        "status": "pre_match"
    },
    {
        "match_id": 2277792,
        "points": 0,
        "team_1": "Inglaterra",
        "team_1_id": 114,
        "team_2": "Ir\u00e1n",
        "team_2_id": 1042,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-21T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 38026,
        "status": "pre_match"
    },
    {
        "match_id": 2277790,
        "points": 0,
        "team_1": "Senegal",
        "team_1_id": 1226,
        "team_2": "Holanda",
        "team_2_id": 366,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-21T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 38206,
        "status": "pre_match"
    },
    {
        "match_id": 2277793,
        "points": 0,
        "team_1": "EE.UU.",
        "team_1_id": 596,
        "team_2": "Gales",
        "team_2_id": 508,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-21T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 38386,
        "status": "pre_match"
    },
    {
        "match_id": 2277794,
        "points": 0,
        "team_1": "Argentina",
        "team_1_id": 632,
        "team_2": "A. Saudita",
        "team_2_id": 1264,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-22T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 39286,
        "status": "pre_match"
    },
    {
        "match_id": 2277798,
        "points": 0,
        "team_1": "Dinamarca",
        "team_1_id": 369,
        "team_2": "T\u00fanez",
        "team_2_id": 1224,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-22T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 39466,
        "status": "pre_match"
    },
    {
        "match_id": 2277795,
        "points": 0,
        "team_1": "M\u00e9xico",
        "team_1_id": 659,
        "team_2": "Polonia",
        "team_2_id": 511,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-22T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 39646,
        "status": "pre_match"
    },
    {
        "match_id": 2277797,
        "points": 0,
        "team_1": "Francia",
        "team_1_id": 368,
        "team_2": "Australia",
        "team_2_id": 575,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-22T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 39826,
        "status": "pre_match"
    },
    {
        "match_id": 2277802,
        "points": 0,
        "team_1": "Marruecos",
        "team_1_id": 1057,
        "team_2": "Croacia",
        "team_2_id": 535,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-11-23T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 40726,
        "status": "pre_match"
    },
    {
        "match_id": 2277800,
        "points": 0,
        "team_1": "Alemania",
        "team_1_id": 357,
        "team_2": "Jap\u00f3n",
        "team_2_id": 1266,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-11-23T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 40906,
        "status": "pre_match"
    },
    {
        "match_id": 2277799,
        "points": 0,
        "team_1": "Espa\u00f1a",
        "team_1_id": 118,
        "team_2": "Costa Rica",
        "team_2_id": 838,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-11-23T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 41086,
        "status": "pre_match"
    },
    {
        "match_id": 2277801,
        "points": 0,
        "team_1": "B\u00e9lgica",
        "team_1_id": 360,
        "team_2": "Canad\u00e1",
        "team_2_id": 597,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-11-23T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 41266,
        "status": "pre_match"
    },
    {
        "match_id": 2277804,
        "points": 0,
        "team_1": "Suiza",
        "team_1_id": 497,
        "team_2": "Camer\u00fan",
        "team_2_id": 494,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-11-24T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 42166,
        "status": "pre_match"
    },
    {
        "match_id": 2277806,
        "points": 0,
        "team_1": "Uruguay",
        "team_1_id": 837,
        "team_2": "R. Corea",
        "team_2_id": 1041,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-11-24T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 42346,
        "status": "pre_match"
    },
    {
        "match_id": 2277805,
        "points": 0,
        "team_1": "Portugal",
        "team_1_id": 359,
        "team_2": "Ghana",
        "team_2_id": 1219,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-11-24T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 42526,
        "status": "pre_match"
    },
    {
        "match_id": 2277803,
        "points": 0,
        "team_1": "Brasil",
        "team_1_id": 614,
        "team_2": "Serbia",
        "team_2_id": 364,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-11-24T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 42706,
        "status": "pre_match"
    },
    {
        "match_id": 2277810,
        "points": 0,
        "team_1": "Gales",
        "team_1_id": 508,
        "team_2": "Ir\u00e1n",
        "team_2_id": 1042,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-25T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 43606,
        "status": "pre_match"
    },
    {
        "match_id": 2277807,
        "points": 0,
        "team_1": "Qatar",
        "team_1_id": 1873,
        "team_2": "Senegal",
        "team_2_id": 1226,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-25T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 43786,
        "status": "pre_match"
    },
    {
        "match_id": 2277808,
        "points": 0,
        "team_1": "Holanda",
        "team_1_id": 366,
        "team_2": "Ecuador",
        "team_2_id": 830,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-25T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 43966,
        "status": "pre_match"
    },
    {
        "match_id": 2277809,
        "points": 0,
        "team_1": "Inglaterra",
        "team_1_id": 114,
        "team_2": "EE.UU.",
        "team_2_id": 596,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-25T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 44146,
        "status": "pre_match"
    },
    {
        "match_id": 2277814,
        "points": 0,
        "team_1": "T\u00fanez",
        "team_1_id": 1224,
        "team_2": "Australia",
        "team_2_id": 575,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-26T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 45046,
        "status": "pre_match"
    },
    {
        "match_id": 2277812,
        "points": 0,
        "team_1": "Polonia",
        "team_1_id": 511,
        "team_2": "A. Saudita",
        "team_2_id": 1264,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-26T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 45226,
        "status": "pre_match"
    },
    {
        "match_id": 2277813,
        "points": 0,
        "team_1": "Francia",
        "team_1_id": 368,
        "team_2": "Dinamarca",
        "team_2_id": 369,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-26T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 45406,
        "status": "pre_match"
    },
    {
        "match_id": 2277811,
        "points": 0,
        "team_1": "Argentina",
        "team_1_id": 632,
        "team_2": "M\u00e9xico",
        "team_2_id": 659,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-26T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 45586,
        "status": "pre_match"
    },
    {
        "match_id": 2277816,
        "points": 0,
        "team_1": "Jap\u00f3n",
        "team_1_id": 1266,
        "team_2": "Costa Rica",
        "team_2_id": 838,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-11-27T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 46486,
        "status": "pre_match"
    },
    {
        "match_id": 2277817,
        "points": 0,
        "team_1": "B\u00e9lgica",
        "team_1_id": 360,
        "team_2": "Marruecos",
        "team_2_id": 1057,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-11-27T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 46666,
        "status": "pre_match"
    },
    {
        "match_id": 2277818,
        "points": 0,
        "team_1": "Croacia",
        "team_1_id": 535,
        "team_2": "Canad\u00e1",
        "team_2_id": 597,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-11-27T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 46846,
        "status": "pre_match"
    },
    {
        "match_id": 2277815,
        "points": 0,
        "team_1": "Espa\u00f1a",
        "team_1_id": 118,
        "team_2": "Alemania",
        "team_2_id": 357,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-11-27T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 47026,
        "status": "pre_match"
    },
    {
        "match_id": 2277820,
        "points": 0,
        "team_1": "Camer\u00fan",
        "team_1_id": 494,
        "team_2": "Serbia",
        "team_2_id": 364,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-11-28T10:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 47926,
        "status": "pre_match"
    },
    {
        "match_id": 2277822,
        "points": 0,
        "team_1": "R. Corea",
        "team_1_id": 1041,
        "team_2": "Ghana",
        "team_2_id": 1219,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-11-28T13:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 48106,
        "status": "pre_match"
    },
    {
        "match_id": 2277819,
        "points": 0,
        "team_1": "Brasil",
        "team_1_id": 614,
        "team_2": "Suiza",
        "team_2_id": 497,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-11-28T16:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 48286,
        "status": "pre_match"
    },
    {
        "match_id": 2277821,
        "points": 0,
        "team_1": "Portugal",
        "team_1_id": 359,
        "team_2": "Uruguay",
        "team_2_id": 837,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-11-28T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 48466,
        "status": "pre_match"
    },
    {
        "match_id": 2277823,
        "points": 0,
        "team_1": "Holanda",
        "team_1_id": 366,
        "team_2": "Qatar",
        "team_2_id": 1873,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-29T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 49666,
        "status": "pre_match"
    },
    {
        "match_id": 2277824,
        "points": 0,
        "team_1": "Ecuador",
        "team_1_id": 830,
        "team_2": "Senegal",
        "team_2_id": 1226,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "A",
        "datetime": "2022-11-29T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 49666,
        "status": "pre_match"
    },
    {
        "match_id": 2277825,
        "points": 0,
        "team_1": "Gales",
        "team_1_id": 508,
        "team_2": "Inglaterra",
        "team_2_id": 114,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-29T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 49906,
        "status": "pre_match"
    },
    {
        "match_id": 2277826,
        "points": 0,
        "team_1": "Ir\u00e1n",
        "team_1_id": 1042,
        "team_2": "EE.UU.",
        "team_2_id": 596,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "B",
        "datetime": "2022-11-29T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 49906,
        "status": "pre_match"
    },
    {
        "match_id": 2277829,
        "points": 0,
        "team_1": "T\u00fanez",
        "team_1_id": 1224,
        "team_2": "Francia",
        "team_2_id": 368,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-30T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 51106,
        "status": "pre_match"
    },
    {
        "match_id": 2277830,
        "points": 0,
        "team_1": "Australia",
        "team_1_id": 575,
        "team_2": "Dinamarca",
        "team_2_id": 369,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "D",
        "datetime": "2022-11-30T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 51106,
        "status": "pre_match"
    },
    {
        "match_id": 2277828,
        "points": 0,
        "team_1": "A. Saudita",
        "team_1_id": 1264,
        "team_2": "M\u00e9xico",
        "team_2_id": 659,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-30T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 51346,
        "status": "pre_match"
    },
    {
        "match_id": 2277827,
        "points": 0,
        "team_1": "Polonia",
        "team_1_id": 511,
        "team_2": "Argentina",
        "team_2_id": 632,
        "goal_1": 1,
        "goal_2": 1,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "C",
        "datetime": "2022-11-30T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 51346,
        "status": "pre_match"
    },
    {
        "match_id": 2277833,
        "points": 0,
        "team_1": "Croacia",
        "team_1_id": 535,
        "team_2": "B\u00e9lgica",
        "team_2_id": 360,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-12-01T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 52546,
        "status": "pre_match"
    },
    {
        "match_id": 2277834,
        "points": 0,
        "team_1": "Canad\u00e1",
        "team_1_id": 597,
        "team_2": "Marruecos",
        "team_2_id": 1057,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "F",
        "datetime": "2022-12-01T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 52546,
        "status": "pre_match"
    },
    {
        "match_id": 2277832,
        "points": 0,
        "team_1": "Costa Rica",
        "team_1_id": 838,
        "team_2": "Alemania",
        "team_2_id": 357,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-12-01T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 52786,
        "status": "pre_match"
    },
    {
        "match_id": 2277831,
        "points": 0,
        "team_1": "Jap\u00f3n",
        "team_1_id": 1266,
        "team_2": "Espa\u00f1a",
        "team_2_id": 118,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "E",
        "datetime": "2022-12-01T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 52786,
        "status": "pre_match"
    },
    {
        "match_id": 2277838,
        "points": 0,
        "team_1": "Ghana",
        "team_1_id": 1219,
        "team_2": "Uruguay",
        "team_2_id": 837,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-12-02T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 53986,
        "status": "pre_match"
    },
    {
        "match_id": 2277837,
        "points": 0,
        "team_1": "R. Corea",
        "team_1_id": 1041,
        "team_2": "Portugal",
        "team_2_id": 359,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "H",
        "datetime": "2022-12-02T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 53986,
        "status": "pre_match"
    },
    {
        "match_id": 2277836,
        "points": 0,
        "team_1": "Serbia",
        "team_1_id": 364,
        "team_2": "Suiza",
        "team_2_id": 497,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-12-02T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 54226,
        "status": "pre_match"
    },
    {
        "match_id": 2277835,
        "points": 0,
        "team_1": "Camer\u00fan",
        "team_1_id": 494,
        "team_2": "Brasil",
        "team_2_id": 614,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "G",
        "datetime": "2022-12-02T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 54226,
        "status": "pre_match"
    },
    {
        "match_id": 2278167,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-03T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 55426,
        "status": "pre_match"
    },
    {
        "match_id": 2278168,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-03T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 55666,
        "status": "pre_match"
    },
    {
        "match_id": 2278169,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-04T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 56866,
        "status": "pre_match"
    },
    {
        "match_id": 2278170,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-04T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 57106,
        "status": "pre_match"
    },
    {
        "match_id": 2278171,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-05T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 58306,
        "status": "pre_match"
    },
    {
        "match_id": 2278172,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-05T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 58546,
        "status": "pre_match"
    },
    {
        "match_id": 2278173,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-06T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 59746,
        "status": "pre_match"
    },
    {
        "match_id": 2278174,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "eighth",
        "datetime": "2022-12-06T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 59986,
        "status": "pre_match"
    },
    {
        "match_id": 2278402,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "fourth",
        "datetime": "2022-12-09T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 64066,
        "status": "pre_match"
    },
    {
        "match_id": 2278399,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "fourth",
        "datetime": "2022-12-09T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 64306,
        "status": "pre_match"
    },
    {
        "match_id": 2278403,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "fourth",
        "datetime": "2022-12-10T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 65506,
        "status": "pre_match"
    },
    {
        "match_id": 2278400,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "fourth",
        "datetime": "2022-12-10T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 65746,
        "status": "pre_match"
    },
    {
        "match_id": 2278404,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "semi",
        "datetime": "2022-12-13T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 70066,
        "status": "pre_match"
    },
    {
        "match_id": 2278406,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "semi",
        "datetime": "2022-12-14T19:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 71506,
        "status": "pre_match"
    },
    {
        "match_id": 2278408,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "final",
        "datetime": "2022-12-17T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 75586,
        "status": "pre_match"
    },
    {
        "match_id": 2278411,
        "points": 0,
        "team_1": null,
        "team_1_id": null,
        "team_2": null,
        "team_2_id": null,
        "goal_1": null,
        "goal_2": null,
        "goal_1_opta": null,
        "goal_2_opta": null,
        "penalty_1_opta": null,
        "penalty_2_opta": null,
        "winner": null,
        "group": "final",
        "datetime": "2022-12-18T15:00:00Z",
        "locked": false,
        "minutes_left_to_start_match": 77026,
        "status": "pre_match"
    }
    ]
    
    
    